- name: Run on localhost
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: docker_deploy

- name: Run on remote hosts
  hosts: all
  become: true
  roles:
    - role: docker_deploy
