- name: Run on localhost
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: docker_deploy
  tags: run_local

- name: Run on remotes
  hosts: all
  become: true
  roles:
    - role: docker_deploy
  tags: run_remote
