- set_fact:
    service_ip: "{{ ansible_default_ipv4.address }}"
  when:
    - loop_var.service_ip is not defined
- set_fact:
    service_ip: "{{ loop_var.service_ip }}"
  when:
    - loop_var.service_ip is defined

- copy:
    content: "{{ nginx_conf_list_var_name }}:"
    dest: "{{ ngninx_conf_dst }}"
    force: no

- blockinfile:
    path: "{{ ngninx_conf_dst }}"
    block: |2
        - service_name: "{{ loop_var.service_name }}"
          service_ip:  "{{ service_ip }}"
          service_port: "{{ loop_var.service_port }}"
          service_url: "{{ loop_var.service_url }}"
    marker: ""
  when:
    - loop_var.service_name is defined
    - loop_var.service_port is defined
    - loop_var.service_url is defined