- name: Install netcat on Alpine
  apk:
    name:
      - netcat-openbsd
  when: ansible_distribution in ["Alpine"]

- name: Copy psot data shell script
  copy:
    src: post_data.sh
    dest: "{{ nginx_post_script_dst }}"

- name: Create cron task to post nginx data
  cron:
    user: root
    name: Post nginx data
    special_time: reboot
    job: "bash {{ nginx_post_script_dst }} {{ nginx_conf_dst }} {{ post_port }}"
