- name: Get list of remotes
  shell: sudo git remote -v
  args:
    chdir: "{{ loop_var.push_repo_dir }}"
  register: git_remotes
  changed_when: false

- set_fact:
    match_found: "{{ loop_var.push_repo_url in git_remotes.stdout }}"

- name: Add push repo
  shell:
    sudo git remote set-url --add --push origin {{ loop_var.push_repo_url }}
  args:
    chdir: "{{ loop_var.push_repo_dir }}"
  when:
    - not match_found

- name: Copy push_repo.sh
  copy:
    src: push_repo.sh
    dest: "{{ push_repo_file }}"
    force: false

- name: Add repo dest to push_repo.sh
  blockinfile:
    path: "{{ push_repo_file }}"
    marker: ""
    block: |
      "{{ loop_var.push_repo_dir }}"
    insertafter: 'REPO_DIRS=\('
    create: no
  when: "'{{ loop_var.push_repo_dir }}' not in lookup('file', '{{ push_repo_file }}')"
