- debug:
    msg: "{{ loop_var.push_repo_url }}"

- name: Get list of remotes
  shell: sudo git remote -v
  args:
    chdir: "{{ loop_var.push_repo_dir }}"
  register: git_remotes
  changed_when: false

- set_fact:
    match_found: "{{ loop_var.push_repo_url in git_remotes.stdout }}"

- debug:
    msg: "{{ match_found }}"

- name: Add push repo
  shell:
    sudo git remote set-url --add --push origin {{ loop_var.push_repo_url }}
  args:
    chdir: "{{ loop_var.push_repo_dir }}"
#  when:
#    - not match_found
