- name: Create cron task to for push repo
  cron:
    user: root
    name: push repos
    hour: 4
    job: "bash {{ push_repo_file }}"

- block:
  - include_tasks: subtasks/deploy_compose.yml
    loop: "{{ lookup('dict', docker_composes, wantlist=True) }}"
    when: docker_composes is defined

- stat:
    path: "{{ nginx_conf_dst }}"
  register: nginx_data_file

- include_tasks: subtasks/setup_post_data.yml
  when:
    - nginx_data_file.stat.exists



- set_fact:
    a: "there"

- template:
    src: /home/jeo/a/sonarr.j2
    dest: /home/jeo/a.txt